# Generated by Django 3.2.8 on 2021-10-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_tasks_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='details',
            new_name='description',
        ),
    ]
