# Generated by Django 3.2.8 on 2021-10-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tasks_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='status',
        ),
    ]
